version: "3.9"

services:
  mongo:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
  node:
    container_name: api
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./dist/:/usr/app/dist
    environment:
      SALT: ${SALT}
      PORT: ${PORT}
      MONGODB_URL: ${MONGODB_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES: ${JWT_EXPIRES}